---
# update
framework: jasmine
preMerge:
  pattern:
    - "spec/**/*.js"
postMerge:
  pattern:
    - "spec/**/*.js"
preRun: 
  command: 
    - npm ci    
postRun:
  command: 
    - echo 'Done Testing'
